### PR TITLE
Create Leaderboard Page

### PR DESCRIPTION
**Pull request by InternetRamen**

### CODE REVIEW

**Comment by InternetRamen** [comment]
image

**Review by zbrachinara — APPROVED** [review]
Ok, looks good to me

**Comment by zbrachinara** [comment]
Keep in mind though that Varun is working on a port to React and NextJS, so merging these changes might not be the best idea right now. I'm about to bug him about hurrying this up though

**Comment by InternetRamen** [comment]
@

**Comment by DefyGG** [comment]
Sounds great! I'll merge once I can get confirmation from Varun

**Pull request merged**
